apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: gcr.io/avian-cable-379805/bakerrang-client:1.0.5
        env:
        - name: REACT_APP_API_URL
          value: "http://34.106.65.248:80"
        ports:
        - containerPort: 3000
